#version 300 es
precision highp float;
precision highp int;
precision highp usampler2D;

// Generated by tools/generate-dctbs2-shaders.js.
// Direct random-access decoder for the current 64-byte-header DCTBS2 v2 format.
uniform highp usampler2D uDctData;
uniform int uDataTexWidth;
uniform bool uFlipY;

in vec2 vTexCoord;
out vec4 outColor;

const float PI = 3.1415926535897932384626433832795;
const int HEADER_SIZE = 64;
const int LIBRARY_HEADER_SIZE = 32;
const uint EXPECTED_MODE = 6000u;
const uint EXPECTED_MCU_BYTES = 192u;
const uint EXPECTED_Y_BYTES = 128u;
const uint EXPECTED_CB_BYTES = 32u;
const uint EXPECTED_CR_BYTES = 32u;
const bool ALLOW_SPLIT_LUMA = true;
const uint FLAG_SPLIT_LUMA = 2u;
const uint FLAG_LIBRARY = 4u;

const int QUANT_Y[64] = int[64](
    16, 11, 10, 16, 24, 40, 51, 61, 12, 12, 14, 19, 26, 58, 60, 55, 14, 13, 16, 24,
    40, 57, 69, 56, 14, 17, 22, 29, 51, 87, 80, 62, 18, 22, 37, 56, 68, 109, 103, 77,
    24, 35, 55, 64, 81, 104, 113, 92, 49, 64, 78, 87, 103, 121, 120, 101, 72, 92, 95, 98,
    112, 100, 103, 99
);

const int QUANT_C[64] = int[64](
    17, 18, 24, 47, 99, 99, 99, 99, 18, 21, 26, 66, 99, 99, 99, 99, 24, 26, 56, 99,
    99, 99, 99, 99, 47, 66, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
    99, 99, 99, 99
);

const int SCAN_Y16[1020] = int[1020](
    16, 1, 2, 17, 32, 48, 33, 18, 3, 4, 19, 34, 49, 64, 80, 65, 50, 35, 20, 5,
    6, 21, 36, 51, 66, 81, 96, 112, 97, 82, 67, 52, 37, 22, 7, 8, 23, 38, 53, 68,
    83, 98, 113, 128, 144, 129, 114, 99, 84, 69, 54, 39, 24, 9, 10, 25, 40, 55, 70, 85,
    100, 115, 130, 145, 160, 176, 161, 146, 131, 116, 101, 86, 71, 56, 41, 26, 11, 12, 27, 42,
    57, 72, 87, 102, 117, 132, 147, 162, 177, 192, 208, 193, 178, 163, 148, 133, 118, 103, 88, 73,
    58, 43, 28, 13, 14, 29, 44, 59, 74, 89, 104, 119, 134, 149, 164, 179, 194, 209, 224, 240,
    225, 210, 195, 180, 165, 150, 135, 120, 105, 90, 75, 60, 45, 30, 15, 31, 46, 61, 76, 91,
    106, 121, 136, 151, 166, 181, 196, 211, 226, 241, 242, 227, 212, 197, 182, 167, 152, 137, 122, 107,
    92, 77, 62, 47, 63, 78, 93, 108, 123, 138, 153, 168, 183, 198, 213, 228, 243, 244, 229, 214,
    199, 184, 169, 154, 139, 124, 109, 94, 79, 95, 110, 125, 140, 155, 170, 185, 200, 215, 230, 245,
    246, 231, 216, 201, 186, 171, 156, 141, 126, 111, 127, 142, 157, 172, 187, 202, 217, 232, 247, 248,
    233, 218, 203, 188, 173, 158, 143, 159, 174, 189, 204, 219, 234, 249, 250, 235, 220, 205, 190, 175,
    191, 206, 221, 236, 251, 252, 237, 222, 207, 223, 238, 253, 254, 239, 255, 1, 2, 16, 3, 17,
    4, 18, 32, 5, 19, 33, 6, 20, 34, 7, 48, 21, 35, 8, 49, 22, 36, 9, 50, 23,
    64, 37, 10, 51, 24, 65, 38, 11, 52, 25, 66, 39, 80, 12, 53, 26, 67, 40, 81, 13,
    54, 27, 68, 41, 82, 14, 55, 96, 28, 69, 42, 83, 15, 56, 97, 29, 70, 43, 84, 57,
    98, 30, 71, 112, 44, 85, 58, 99, 31, 72, 113, 45, 86, 59, 100, 73, 114, 46, 87, 128,
    60, 101, 74, 115, 47, 88, 129, 61, 102, 75, 116, 89, 130, 62, 103, 144, 76, 117, 90, 131,
    63, 104, 145, 77, 118, 91, 132, 105, 146, 78, 119, 160, 92, 133, 106, 147, 79, 120, 161, 93,
    134, 107, 148, 121, 162, 94, 135, 176, 108, 149, 122, 163, 95, 136, 177, 109, 150, 123, 164, 137,
    178, 110, 151, 192, 124, 165, 138, 179, 111, 152, 193, 125, 166, 139, 180, 153, 194, 126, 167, 208,
    140, 181, 154, 195, 127, 168, 209, 141, 182, 155, 196, 169, 210, 142, 183, 156, 224, 197, 170, 211,
    143, 184, 157, 225, 198, 171, 212, 185, 158, 226, 199, 240, 172, 213, 186, 159, 227, 200, 241, 173,
    214, 187, 228, 201, 242, 174, 215, 188, 229, 202, 243, 175, 216, 189, 230, 203, 244, 217, 190, 231,
    204, 245, 218, 191, 232, 205, 246, 219, 233, 206, 247, 220, 234, 207, 248, 221, 235, 249, 222, 236,
    250, 223, 237, 251, 238, 252, 239, 253, 254, 255, 16, 32, 1, 48, 17, 64, 33, 2, 80, 49,
    18, 96, 65, 34, 112, 3, 81, 50, 128, 19, 97, 66, 144, 35, 113, 4, 82, 160, 51, 129,
    20, 98, 176, 67, 145, 36, 114, 5, 192, 83, 161, 52, 130, 21, 208, 99, 177, 68, 146, 37,
    224, 115, 6, 193, 84, 162, 53, 240, 131, 22, 209, 100, 178, 69, 147, 38, 225, 116, 7, 194,
    85, 163, 54, 241, 132, 23, 210, 101, 179, 70, 148, 39, 226, 117, 8, 195, 86, 164, 55, 242,
    133, 24, 211, 102, 180, 71, 149, 40, 227, 118, 9, 196, 87, 165, 56, 243, 134, 25, 212, 103,
    181, 72, 150, 41, 228, 119, 10, 197, 88, 166, 57, 244, 135, 26, 213, 104, 182, 73, 151, 42,
    229, 120, 11, 198, 89, 167, 58, 245, 136, 27, 214, 105, 183, 74, 152, 43, 230, 121, 12, 199,
    90, 168, 59, 246, 137, 28, 215, 106, 184, 75, 153, 44, 231, 122, 13, 200, 91, 169, 60, 247,
    138, 29, 216, 107, 185, 76, 154, 45, 232, 123, 201, 14, 92, 170, 61, 248, 139, 217, 30, 108,
    186, 77, 155, 233, 46, 124, 15, 202, 93, 171, 249, 62, 140, 31, 218, 109, 187, 78, 156, 47,
    234, 125, 203, 94, 172, 63, 250, 141, 219, 110, 188, 79, 157, 235, 126, 204, 95, 173, 251, 142,
    220, 111, 189, 158, 236, 127, 205, 174, 252, 143, 221, 190, 159, 237, 206, 175, 253, 222, 191, 238,
    207, 254, 223, 239, 255, 17, 1, 16, 34, 18, 33, 2, 32, 51, 35, 50, 19, 49, 3, 48,
    68, 52, 67, 36, 66, 20, 65, 4, 64, 85, 69, 84, 53, 83, 37, 82, 21, 81, 5, 80,
    102, 86, 101, 70, 100, 54, 99, 38, 98, 22, 97, 6, 96, 119, 103, 118, 87, 117, 71, 116,
    55, 115, 39, 114, 23, 113, 7, 112, 136, 120, 135, 104, 134, 88, 133, 72, 132, 56, 131, 40,
    130, 24, 129, 8, 128, 153, 137, 152, 121, 151, 105, 150, 89, 149, 73, 148, 57, 147, 41, 146,
    25, 145, 9, 144, 170, 154, 169, 138, 168, 122, 167, 106, 166, 90, 165, 74, 164, 58, 163, 42,
    162, 26, 161, 10, 160, 187, 171, 186, 155, 185, 139, 184, 123, 183, 107, 182, 91, 181, 75, 180,
    59, 179, 43, 178, 27, 177, 11, 176, 204, 188, 203, 172, 202, 156, 201, 140, 200, 124, 199, 108,
    198, 92, 197, 76, 196, 60, 195, 44, 194, 28, 193, 12, 192, 221, 205, 220, 189, 219, 173, 218,
    157, 217, 141, 216, 125, 215, 109, 214, 93, 213, 77, 212, 61, 211, 45, 210, 29, 209, 13, 208,
    238, 222, 237, 206, 236, 190, 235, 174, 234, 158, 233, 142, 232, 126, 231, 110, 230, 94, 229, 78,
    228, 62, 227, 46, 226, 30, 225, 14, 224, 255, 239, 254, 223, 253, 207, 252, 191, 251, 175, 250,
    159, 249, 143, 248, 127, 247, 111, 246, 95, 245, 79, 244, 63, 243, 47, 242, 31, 241, 15, 240
);

const int SCAN_Y8[252] = int[252](
    8, 1, 2, 9, 16, 24, 17, 10, 3, 4, 11, 18, 25, 32, 40, 33, 26, 19, 12, 5,
    6, 13, 20, 27, 34, 41, 48, 56, 49, 42, 35, 28, 21, 14, 7, 15, 22, 29, 36, 43,
    50, 57, 58, 51, 44, 37, 30, 23, 31, 38, 45, 52, 59, 60, 53, 46, 39, 47, 54, 61,
    62, 55, 63, 1, 2, 8, 3, 9, 4, 10, 16, 5, 11, 17, 6, 12, 18, 7, 24, 13,
    19, 25, 14, 20, 26, 15, 32, 21, 27, 33, 22, 28, 34, 23, 40, 29, 35, 41, 30, 36,
    42, 31, 48, 37, 43, 49, 38, 44, 50, 39, 56, 45, 51, 57, 46, 52, 58, 47, 53, 59,
    54, 60, 55, 61, 62, 63, 8, 16, 1, 24, 9, 32, 17, 2, 40, 25, 10, 48, 33, 18,
    56, 3, 41, 26, 11, 49, 34, 19, 57, 4, 42, 27, 12, 50, 35, 20, 58, 5, 43, 28,
    13, 51, 36, 21, 59, 6, 44, 29, 14, 52, 37, 22, 60, 7, 45, 30, 15, 53, 38, 23,
    61, 46, 31, 54, 39, 62, 47, 55, 63, 9, 1, 8, 18, 10, 17, 2, 16, 27, 19, 26,
    11, 25, 3, 24, 36, 28, 35, 20, 34, 12, 33, 4, 32, 45, 37, 44, 29, 43, 21, 42,
    13, 41, 5, 40, 54, 46, 53, 38, 52, 30, 51, 22, 50, 14, 49, 6, 48, 63, 55, 62,
    47, 61, 39, 60, 31, 59, 23, 58, 15, 57, 7, 56
);

const int SCAN_C[508] = int[508](
    8, 1, 2, 9, 16, 24, 17, 10, 3, 4, 11, 18, 25, 32, 40, 33, 26, 19, 12, 5,
    6, 13, 20, 27, 34, 41, 48, 56, 49, 42, 35, 28, 21, 14, 7, 15, 22, 29, 36, 43,
    50, 57, 64, 72, 65, 58, 51, 44, 37, 30, 23, 31, 38, 45, 52, 59, 66, 73, 80, 88,
    81, 74, 67, 60, 53, 46, 39, 47, 54, 61, 68, 75, 82, 89, 96, 104, 97, 90, 83, 76,
    69, 62, 55, 63, 70, 77, 84, 91, 98, 105, 112, 120, 113, 106, 99, 92, 85, 78, 71, 79,
    86, 93, 100, 107, 114, 121, 122, 115, 108, 101, 94, 87, 95, 102, 109, 116, 123, 124, 117, 110,
    103, 111, 118, 125, 126, 119, 127, 1, 2, 8, 3, 9, 4, 10, 16, 5, 11, 17, 6, 12,
    18, 7, 24, 13, 19, 25, 14, 20, 26, 15, 32, 21, 27, 33, 22, 28, 34, 23, 40, 29,
    35, 41, 30, 36, 42, 31, 48, 37, 43, 49, 38, 44, 50, 39, 56, 45, 51, 57, 46, 52,
    58, 47, 64, 53, 59, 65, 54, 60, 66, 55, 72, 61, 67, 73, 62, 68, 74, 63, 80, 69,
    75, 81, 70, 76, 82, 71, 88, 77, 83, 89, 78, 84, 90, 79, 96, 85, 91, 97, 86, 92,
    98, 87, 104, 93, 99, 105, 94, 100, 106, 95, 112, 101, 107, 113, 102, 108, 114, 103, 120, 109,
    115, 121, 110, 116, 122, 111, 117, 123, 118, 124, 119, 125, 126, 127, 8, 16, 1, 24, 9, 32,
    17, 2, 40, 25, 10, 48, 33, 18, 56, 3, 41, 26, 64, 11, 49, 34, 72, 19, 57, 4,
    42, 80, 27, 65, 12, 50, 88, 35, 73, 20, 58, 5, 96, 43, 81, 28, 66, 13, 104, 51,
    89, 36, 74, 21, 112, 59, 6, 97, 44, 82, 29, 120, 67, 14, 105, 52, 90, 37, 75, 22,
    113, 60, 7, 98, 45, 83, 30, 121, 68, 15, 106, 53, 91, 38, 76, 23, 114, 61, 99, 46,
    84, 31, 122, 69, 107, 54, 92, 39, 77, 115, 62, 100, 47, 85, 123, 70, 108, 55, 93, 78,
    116, 63, 101, 86, 124, 71, 109, 94, 79, 117, 102, 87, 125, 110, 95, 118, 103, 126, 111, 119,
    127, 9, 1, 8, 18, 10, 17, 2, 16, 27, 19, 26, 11, 25, 3, 24, 36, 28, 35, 20,
    34, 12, 33, 4, 32, 45, 37, 44, 29, 43, 21, 42, 13, 41, 5, 40, 54, 46, 53, 38,
    52, 30, 51, 22, 50, 14, 49, 6, 48, 63, 55, 62, 47, 61, 39, 60, 31, 59, 23, 58,
    15, 57, 7, 56, 71, 70, 69, 68, 67, 66, 65, 64, 79, 78, 77, 76, 75, 74, 73, 72,
    87, 86, 85, 84, 83, 82, 81, 80, 95, 94, 93, 92, 91, 90, 89, 88, 103, 102, 101, 100,
    99, 98, 97, 96, 111, 110, 109, 108, 107, 106, 105, 104, 119, 118, 117, 116, 115, 114, 113, 112,
    127, 126, 125, 124, 123, 122, 121, 120
);

const int SKIP_SCAN_Y16[2040] = int[2040](
    1, 16, 17, 2, 32, 18, 33, 34, 3, 48, 19, 49, 35, 50, 4, 64, 20, 65, 51, 36,
    66, 5, 80, 52, 67, 21, 81, 37, 82, 68, 53, 83, 6, 96, 22, 97, 38, 98, 69, 84,
    54, 99, 7, 112, 23, 113, 85, 70, 100, 39, 114, 55, 115, 86, 101, 8, 128, 24, 129, 71,
    116, 40, 130, 102, 56, 131, 87, 117, 72, 132, 9, 144, 25, 145, 41, 146, 103, 118, 88, 133,
    57, 147, 73, 148, 119, 10, 160, 104, 134, 26, 161, 42, 162, 89, 149, 58, 163, 120, 135, 74,
    164, 105, 150, 11, 176, 27, 177, 43, 178, 90, 165, 136, 59, 179, 121, 151, 106, 166, 75, 180,
    12, 192, 137, 152, 28, 193, 91, 181, 44, 194, 122, 167, 60, 195, 107, 182, 76, 196, 153, 138,
    168, 13, 208, 92, 197, 29, 209, 123, 183, 45, 210, 61, 211, 108, 198, 154, 169, 77, 212, 139,
    184, 124, 199, 93, 213, 14, 224, 30, 225, 46, 226, 170, 155, 185, 62, 227, 109, 214, 140, 200,
    78, 228, 125, 215, 171, 186, 94, 229, 15, 240, 156, 201, 31, 241, 47, 242, 110, 230, 141, 216,
    63, 243, 79, 244, 187, 172, 202, 126, 231, 95, 245, 157, 217, 142, 232, 111, 246, 188, 203, 173,
    218, 127, 247, 158, 233, 204, 143, 248, 189, 219, 174, 234, 159, 249, 205, 220, 190, 235, 175, 250,
    221, 206, 236, 191, 251, 222, 237, 207, 252, 238, 223, 253, 239, 254, 255, 1, 2, 3, 16, 17,
    18, 4, 19, 5, 20, 21, 6, 32, 33, 34, 22, 35, 7, 36, 23, 37, 8, 24, 38, 9,
    48, 49, 39, 50, 25, 51, 10, 52, 40, 26, 53, 41, 11, 54, 27, 55, 42, 12, 56, 64,
    28, 65, 66, 43, 67, 57, 68, 13, 69, 29, 44, 58, 70, 14, 71, 30, 59, 45, 72, 15,
    60, 73, 46, 31, 80, 81, 82, 83, 74, 84, 61, 47, 85, 75, 86, 62, 87, 76, 88, 63,
    89, 77, 90, 96, 97, 98, 78, 99, 91, 100, 101, 79, 102, 92, 103, 93, 104, 105, 94, 106,
    95, 107, 112, 113, 114, 115, 116, 108, 117, 118, 109, 119, 120, 110, 121, 122, 111, 123, 128, 124,
    129, 130, 131, 132, 133, 125, 134, 135, 126, 136, 137, 127, 138, 139, 140, 144, 145, 146, 141, 147,
    148, 149, 142, 150, 151, 143, 152, 153, 154, 155, 156, 157, 160, 161, 162, 163, 158, 164, 165, 166,
    159, 167, 168, 169, 170, 171, 172, 173, 174, 176, 177, 178, 179, 180, 175, 181, 182, 183, 184, 185,
    186, 187, 188, 189, 190, 192, 193, 194, 191, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
    206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
    226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
    246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 16, 32, 48, 1, 17, 33, 64, 49, 80, 65,
    81, 96, 2, 18, 34, 97, 50, 112, 66, 113, 82, 128, 129, 98, 144, 3, 19, 114, 35, 145,
    51, 160, 67, 130, 161, 83, 146, 176, 99, 177, 115, 162, 192, 131, 4, 193, 20, 36, 178, 52,
    147, 68, 208, 84, 209, 194, 163, 100, 224, 116, 225, 179, 210, 132, 240, 195, 148, 226, 241, 5,
    21, 37, 53, 164, 69, 211, 242, 85, 180, 101, 227, 117, 196, 133, 243, 149, 212, 165, 6, 22,
    38, 228, 54, 181, 70, 86, 244, 102, 197, 118, 213, 134, 150, 229, 166, 245, 182, 7, 23, 39,
    55, 71, 198, 87, 103, 214, 119, 135, 230, 151, 167, 246, 183, 8, 199, 24, 40, 56, 72, 88,
    215, 104, 120, 231, 136, 152, 247, 168, 184, 200, 9, 25, 41, 216, 57, 73, 89, 232, 105, 121,
    248, 137, 153, 169, 185, 201, 217, 10, 26, 42, 58, 233, 74, 90, 106, 249, 122, 138, 154, 170,
    186, 202, 218, 234, 11, 27, 43, 59, 75, 250, 91, 107, 123, 139, 155, 171, 187, 203, 219, 235,
    12, 28, 44, 251, 60, 76, 92, 108, 124, 140, 156, 172, 188, 204, 220, 236, 252, 13, 29, 45,
    61, 77, 93, 109, 125, 141, 157, 173, 189, 205, 221, 237, 253, 14, 30, 46, 62, 78, 94, 110,
    126, 142, 158, 174, 190, 206, 222, 238, 254, 15, 31, 47, 63, 79, 95, 111, 127, 143, 159, 175,
    191, 207, 223, 239, 255, 1, 16, 2, 32, 3, 48, 17, 4, 64, 18, 33, 19, 49, 5, 80,
    20, 65, 6, 96, 21, 81, 7, 112, 22, 97, 34, 35, 50, 23, 113, 8, 128, 36, 66, 24,
    129, 37, 82, 9, 144, 38, 98, 25, 145, 10, 160, 39, 114, 26, 161, 40, 130, 11, 176, 51,
    41, 146, 27, 177, 52, 67, 12, 192, 53, 83, 42, 162, 54, 99, 28, 193, 55, 115, 13, 208,
    43, 178, 29, 209, 56, 131, 14, 224, 44, 194, 57, 147, 30, 225, 58, 163, 45, 210, 15, 240,
    68, 69, 84, 31, 241, 59, 179, 70, 100, 46, 226, 71, 116, 60, 195, 72, 132, 47, 242, 61,
    211, 73, 148, 74, 164, 62, 227, 75, 180, 63, 243, 76, 196, 85, 86, 101, 87, 117, 77, 212,
    88, 133, 78, 228, 89, 149, 90, 165, 79, 244, 91, 181, 92, 197, 93, 213, 102, 103, 118, 94,
    229, 104, 134, 95, 245, 105, 150, 106, 166, 107, 182, 108, 198, 109, 214, 110, 230, 119, 111, 246,
    120, 135, 121, 151, 122, 167, 123, 183, 124, 199, 125, 215, 126, 231, 127, 247, 136, 137, 152, 138,
    168, 139, 184, 140, 200, 141, 216, 142, 232, 143, 248, 153, 154, 169, 155, 185, 156, 201, 157, 217,
    158, 233, 159, 249, 170, 171, 186, 172, 202, 173, 218, 174, 234, 175, 250, 187, 188, 203, 189, 219,
    190, 235, 191, 251, 204, 205, 220, 206, 236, 207, 252, 221, 222, 237, 223, 253, 238, 239, 254, 255,
    17, 34, 51, 1, 16, 68, 18, 33, 35, 50, 85, 52, 67, 2, 32, 19, 49, 69, 84, 102,
    36, 66, 86, 101, 53, 83, 3, 48, 119, 20, 65, 70, 100, 103, 118, 37, 82, 136, 4, 64,
    54, 99, 87, 117, 21, 81, 120, 135, 71, 116, 38, 98, 104, 134, 153, 5, 80, 55, 115, 137,
    152, 88, 133, 22, 97, 121, 151, 72, 132, 39, 114, 170, 105, 150, 6, 96, 154, 169, 56, 131,
    89, 149, 23, 113, 138, 168, 122, 167, 40, 130, 73, 148, 187, 7, 112, 106, 166, 171, 186, 155,
    185, 57, 147, 24, 129, 90, 165, 139, 184, 41, 146, 123, 183, 74, 164, 204, 8, 128, 188, 203,
    107, 182, 172, 202, 58, 163, 25, 145, 156, 201, 91, 181, 140, 200, 42, 162, 124, 199, 75, 180,
    9, 144, 221, 205, 220, 189, 219, 108, 198, 173, 218, 26, 161, 59, 179, 157, 217, 92, 197, 141,
    216, 43, 178, 10, 160, 76, 196, 125, 215, 238, 222, 237, 206, 236, 190, 235, 109, 214, 27, 177,
    60, 195, 174, 234, 158, 233, 93, 213, 142, 232, 44, 194, 11, 176, 77, 212, 126, 231, 239, 254,
    255, 223, 253, 207, 252, 28, 193, 110, 230, 191, 251, 61, 211, 175, 250, 94, 229, 159, 249, 12,
    192, 45, 210, 143, 248, 78, 228, 127, 247, 29, 209, 111, 246, 62, 227, 95, 245, 13, 208, 46,
    226, 79, 244, 30, 225, 63, 243, 14, 224, 47, 242, 31, 241, 15, 240, 1, 16, 2, 32, 17,
    3, 48, 18, 33, 4, 64, 19, 49, 34, 5, 80, 20, 65, 35, 50, 21, 81, 6, 96, 36,
    66, 51, 22, 97, 37, 82, 7, 112, 52, 67, 38, 98, 23, 113, 53, 83, 8, 128, 68, 39,
    114, 54, 99, 24, 129, 69, 84, 9, 144, 55, 115, 40, 130, 70, 100, 25, 145, 85, 56, 131,
    71, 116, 10, 160, 41, 146, 86, 101, 26, 161, 72, 132, 57, 147, 87, 117, 11, 176, 42, 162,
    102, 27, 177, 73, 148, 88, 133, 58, 163, 103, 118, 43, 178, 12, 192, 89, 149, 74, 164, 104,
    134, 28, 193, 59, 179, 119, 44, 194, 90, 165, 13, 208, 105, 150, 75, 180, 120, 135, 29, 209,
    60, 195, 106, 166, 91, 181, 121, 151, 45, 210, 76, 196, 14, 224, 136, 61, 211, 30, 225, 107,
    182, 122, 167, 92, 197, 137, 152, 46, 226, 77, 212, 15, 240, 123, 183, 62, 227, 108, 198, 138,
    168, 31, 241, 93, 213, 153, 47, 242, 78, 228, 124, 199, 139, 184, 109, 214, 154, 169, 63, 243,
    94, 229, 79, 244, 140, 200, 125, 215, 155, 185, 110, 230, 170, 95, 245, 141, 216, 156, 201, 126,
    231, 171, 186, 111, 246, 157, 217, 142, 232, 172, 202, 127, 247, 187, 158, 233, 173, 218, 143, 248,
    188, 203, 174, 234, 159, 249, 189, 219, 204, 175, 250, 190, 235, 205, 220, 191, 251, 206, 236, 221,
    207, 252, 222, 237, 223, 253, 238, 239, 254, 255, 21, 81, 52, 67, 5, 80, 37, 82, 36, 66,
    68, 51, 20, 65, 53, 83, 4, 64, 6, 96, 22, 97, 35, 50, 38, 98, 69, 84, 19, 49,
    3, 48, 34, 54, 99, 7, 112, 23, 113, 85, 18, 33, 70, 100, 2, 32, 39, 114, 55, 115,
    17, 86, 101, 1, 16, 8, 128, 24, 129, 71, 116, 40, 130, 102, 56, 131, 87, 117, 72, 132,
    9, 144, 25, 145, 41, 146, 103, 118, 88, 133, 57, 147, 73, 148, 119, 10, 160, 104, 134, 26,
    161, 42, 162, 89, 149, 58, 163, 120, 135, 74, 164, 105, 150, 11, 176, 27, 177, 43, 178, 90,
    165, 136, 59, 179, 121, 151, 106, 166, 75, 180, 12, 192, 137, 152, 28, 193, 91, 181, 44, 194,
    122, 167, 60, 195, 107, 182, 76, 196, 153, 138, 168, 13, 208, 92, 197, 29, 209, 123, 183, 45,
    210, 61, 211, 108, 198, 154, 169, 77, 212, 139, 184, 124, 199, 93, 213, 14, 224, 30, 225, 46,
    226, 170, 155, 185, 62, 227, 109, 214, 140, 200, 78, 228, 125, 215, 94, 229, 171, 186, 15, 240,
    156, 201, 31, 241, 47, 242, 110, 230, 141, 216, 63, 243, 79, 244, 187, 172, 202, 126, 231, 95,
    245, 157, 217, 142, 232, 111, 246, 188, 203, 173, 218, 127, 247, 158, 233, 204, 143, 248, 189, 219,
    174, 234, 159, 249, 205, 220, 190, 235, 175, 250, 221, 206, 236, 191, 251, 222, 237, 207, 252, 238,
    223, 253, 239, 254, 255, 8, 128, 24, 129, 55, 115, 86, 101, 40, 130, 71, 116, 39, 114, 7,
    112, 23, 113, 70, 100, 56, 131, 9, 144, 85, 102, 87, 117, 25, 145, 54, 99, 72, 132, 41,
    146, 38, 98, 69, 84, 6, 96, 22, 97, 57, 147, 103, 118, 88, 133, 10, 160, 53, 83, 26,
    161, 73, 148, 68, 42, 162, 37, 82, 119, 5, 80, 104, 134, 21, 81, 58, 163, 89, 149, 52,
    67, 11, 176, 27, 177, 74, 164, 36, 66, 120, 135, 43, 178, 105, 150, 20, 65, 4, 64, 51,
    90, 165, 59, 179, 12, 192, 121, 151, 75, 180, 136, 28, 193, 35, 50, 106, 166, 44, 194, 19,
    49, 91, 181, 3, 48, 60, 195, 137, 152, 122, 167, 34, 13, 208, 76, 196, 107, 182, 29, 209,
    45, 210, 18, 33, 92, 197, 2, 32, 138, 168, 153, 61, 211, 123, 183, 14, 224, 77, 212, 108,
    198, 30, 225, 17, 46, 226, 154, 169, 139, 184, 93, 213, 124, 199, 1, 16, 62, 227, 109, 214,
    78, 228, 15, 240, 155, 185, 31, 241, 170, 140, 200, 47, 242, 94, 229, 125, 215, 63, 243, 110,
    230, 171, 186, 156, 201, 79, 244, 141, 216, 95, 245, 126, 231, 172, 202, 187, 157, 217, 111, 246,
    142, 232, 127, 247, 188, 203, 173, 218, 158, 233, 143, 248, 189, 219, 204, 174, 234, 159, 249, 205,
    220, 190, 235, 175, 250, 206, 236, 221, 191, 251, 222, 237, 207, 252, 223, 253, 238, 239, 254, 255
);

const int SKIP_SCAN_Y8[504] = int[504](
    1, 8, 9, 2, 16, 10, 17, 18, 3, 24, 11, 25, 19, 26, 4, 32, 12, 33, 27, 20,
    34, 28, 35, 5, 40, 13, 41, 21, 42, 36, 29, 43, 6, 48, 14, 49, 22, 50, 37, 44,
    30, 51, 7, 56, 15, 57, 45, 38, 52, 23, 58, 31, 59, 46, 53, 39, 60, 54, 47, 61,
    55, 62, 63, 1, 2, 3, 8, 9, 10, 4, 11, 5, 12, 13, 6, 16, 17, 18, 14, 19,
    7, 20, 15, 21, 22, 24, 25, 23, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
    38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
    58, 59, 60, 61, 62, 63, 8, 16, 24, 1, 9, 17, 32, 25, 40, 33, 41, 48, 2, 10,
    18, 49, 26, 56, 34, 57, 42, 50, 3, 11, 58, 19, 27, 35, 43, 51, 59, 4, 12, 20,
    28, 36, 44, 52, 60, 5, 13, 21, 29, 37, 45, 53, 61, 6, 14, 22, 30, 38, 46, 54,
    62, 7, 15, 23, 31, 39, 47, 55, 63, 1, 8, 2, 16, 3, 24, 9, 4, 32, 10, 17,
    11, 25, 5, 40, 12, 33, 6, 48, 13, 41, 7, 56, 14, 49, 18, 19, 26, 15, 57, 20,
    34, 21, 42, 22, 50, 23, 58, 27, 28, 35, 29, 43, 30, 51, 31, 59, 36, 37, 44, 38,
    52, 39, 60, 45, 46, 53, 47, 61, 54, 55, 62, 63, 9, 18, 1, 8, 27, 10, 17, 19,
    26, 2, 16, 36, 11, 25, 28, 35, 20, 34, 3, 24, 45, 37, 44, 12, 33, 29, 43, 21,
    42, 4, 32, 54, 46, 53, 38, 52, 13, 41, 30, 51, 5, 40, 22, 50, 63, 55, 62, 47,
    61, 14, 49, 39, 60, 31, 59, 6, 48, 23, 58, 15, 57, 7, 56, 1, 8, 2, 16, 9,
    10, 17, 3, 24, 11, 25, 18, 4, 32, 19, 26, 12, 33, 5, 40, 20, 34, 27, 13, 41,
    6, 48, 28, 35, 21, 42, 14, 49, 29, 43, 36, 22, 50, 7, 56, 15, 57, 37, 44, 30,
    51, 23, 58, 38, 52, 45, 31, 59, 46, 53, 39, 60, 47, 61, 54, 55, 62, 63, 10, 17,
    2, 16, 18, 3, 24, 9, 11, 25, 1, 8, 19, 26, 4, 32, 12, 33, 27, 20, 34, 28,
    35, 5, 40, 13, 41, 21, 42, 36, 29, 43, 6, 48, 14, 49, 22, 50, 37, 44, 30, 51,
    7, 56, 15, 57, 45, 38, 52, 23, 58, 31, 59, 46, 53, 39, 60, 54, 47, 61, 55, 62,
    63, 19, 26, 4, 32, 11, 25, 12, 33, 3, 24, 27, 18, 20, 34, 5, 40, 10, 17, 13,
    41, 2, 16, 28, 35, 21, 42, 9, 6, 48, 36, 29, 43, 14, 49, 1, 8, 22, 50, 37,
    44, 7, 56, 30, 51, 15, 57, 23, 58, 45, 38, 52, 31, 59, 46, 53, 39, 60, 54, 47,
    61, 55, 62, 63
);

const int SKIP_SCAN_C[1016] = int[1016](
    8, 16, 1, 9, 17, 24, 25, 32, 2, 10, 33, 18, 40, 26, 41, 34, 48, 49, 3, 11,
    42, 19, 56, 27, 57, 50, 35, 64, 43, 58, 65, 4, 12, 51, 20, 72, 66, 28, 73, 36,
    59, 44, 74, 80, 81, 67, 52, 5, 13, 82, 21, 88, 75, 60, 29, 89, 37, 68, 90, 45,
    83, 96, 97, 53, 76, 91, 98, 61, 6, 14, 104, 22, 84, 105, 30, 69, 38, 99, 106, 46,
    92, 77, 112, 113, 54, 107, 62, 114, 85, 100, 7, 120, 15, 23, 70, 121, 31, 93, 115, 39,
    108, 122, 78, 47, 101, 55, 86, 123, 116, 63, 109, 94, 71, 124, 79, 102, 117, 87, 110, 125,
    95, 118, 103, 126, 111, 119, 127, 1, 8, 9, 2, 10, 16, 3, 17, 11, 18, 4, 19, 12,
    24, 25, 26, 20, 5, 13, 27, 32, 21, 33, 28, 6, 34, 14, 35, 29, 22, 7, 36, 15,
    40, 41, 30, 42, 23, 37, 43, 31, 44, 38, 48, 49, 45, 50, 39, 51, 46, 52, 53, 47,
    56, 57, 58, 54, 59, 60, 55, 61, 64, 65, 66, 62, 67, 68, 63, 69, 72, 70, 73, 74,
    75, 71, 76, 77, 78, 80, 81, 82, 83, 79, 84, 85, 86, 88, 89, 90, 87, 91, 92, 93,
    94, 96, 97, 95, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
    114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 8, 16, 24, 32, 40, 48,
    1, 9, 17, 56, 25, 33, 64, 41, 49, 72, 57, 80, 65, 88, 73, 81, 96, 89, 104, 2,
    10, 18, 26, 97, 34, 112, 42, 50, 105, 58, 120, 66, 113, 74, 121, 82, 90, 98, 106, 114,
    3, 11, 19, 122, 27, 35, 43, 51, 59, 67, 75, 83, 91, 99, 107, 115, 123, 4, 12, 20,
    28, 36, 44, 52, 60, 68, 76, 84, 92, 100, 108, 116, 124, 5, 13, 21, 29, 37, 45, 53,
    61, 69, 77, 85, 93, 101, 109, 117, 125, 6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86,
    94, 102, 110, 118, 126, 7, 15, 23, 31, 39, 47, 55, 63, 71, 79, 87, 95, 103, 111, 119,
    127, 8, 16, 1, 24, 32, 9, 2, 40, 10, 48, 3, 56, 11, 17, 64, 25, 18, 4, 33,
    72, 41, 12, 19, 49, 80, 57, 5, 88, 65, 20, 13, 26, 73, 96, 81, 27, 6, 21, 104,
    14, 89, 28, 112, 97, 22, 7, 120, 105, 34, 29, 15, 35, 113, 42, 23, 50, 30, 121, 36,
    58, 66, 74, 37, 82, 31, 90, 43, 38, 98, 44, 106, 39, 114, 45, 122, 46, 51, 52, 47,
    53, 59, 67, 75, 54, 83, 91, 99, 55, 107, 60, 115, 61, 123, 62, 63, 68, 69, 70, 76,
    71, 84, 92, 100, 108, 116, 77, 124, 78, 79, 85, 86, 87, 93, 101, 109, 117, 125, 94, 95,
    102, 103, 110, 118, 126, 111, 119, 127, 17, 8, 25, 9, 34, 16, 42, 26, 1, 33, 18, 51,
    24, 50, 59, 43, 41, 10, 35, 32, 2, 58, 27, 49, 67, 68, 40, 76, 60, 19, 52, 66,
    57, 75, 11, 44, 48, 84, 36, 3, 74, 65, 85, 28, 83, 93, 77, 56, 69, 20, 92, 61,
    73, 82, 53, 12, 64, 91, 101, 45, 100, 4, 37, 81, 90, 102, 72, 110, 94, 29, 99, 86,
    109, 78, 21, 70, 108, 89, 62, 98, 80, 13, 118, 54, 107, 117, 46, 5, 116, 97, 88, 38,
    106, 119, 127, 111, 115, 126, 30, 103, 95, 125, 87, 22, 79, 105, 124, 96, 71, 114, 63, 14,
    123, 55, 6, 47, 113, 104, 122, 39, 31, 112, 121, 23, 15, 7, 120, 8, 16, 1, 24, 9,
    32, 2, 17, 40, 10, 25, 48, 33, 18, 3, 41, 56, 11, 26, 49, 19, 64, 34, 57, 4,
    27, 42, 72, 12, 65, 50, 35, 20, 80, 58, 73, 43, 28, 5, 66, 88, 81, 36, 13, 51,
    21, 74, 44, 96, 89, 59, 29, 82, 67, 52, 6, 37, 97, 104, 14, 90, 75, 60, 45, 22,
    105, 112, 83, 98, 30, 53, 68, 38, 91, 113, 7, 120, 61, 106, 76, 46, 15, 99, 23, 84,
    69, 121, 114, 54, 31, 107, 92, 77, 62, 39, 122, 100, 115, 47, 70, 85, 55, 108, 123, 78,
    93, 63, 116, 101, 86, 71, 124, 109, 94, 79, 117, 87, 102, 125, 95, 110, 118, 103, 126, 111,
    119, 127, 40, 26, 18, 41, 33, 10, 2, 34, 32, 48, 25, 49, 3, 11, 24, 42, 17, 19,
    56, 9, 27, 1, 16, 57, 50, 35, 8, 64, 43, 58, 65, 4, 12, 51, 20, 72, 66, 28,
    73, 36, 59, 44, 74, 80, 81, 67, 52, 5, 13, 82, 21, 88, 75, 60, 29, 89, 37, 68,
    90, 45, 83, 96, 97, 53, 76, 91, 98, 61, 6, 14, 104, 22, 84, 105, 30, 69, 38, 99,
    106, 46, 92, 77, 112, 113, 54, 107, 62, 114, 85, 100, 7, 120, 15, 23, 70, 121, 31, 93,
    115, 39, 108, 122, 78, 47, 101, 55, 86, 123, 116, 63, 109, 94, 71, 124, 79, 102, 117, 87,
    110, 125, 95, 118, 103, 126, 111, 119, 127, 64, 35, 57, 65, 4, 56, 58, 43, 50, 12, 27,
    72, 20, 19, 3, 11, 28, 51, 49, 42, 73, 66, 48, 36, 80, 34, 59, 41, 74, 44, 81,
    40, 26, 5, 13, 67, 88, 52, 18, 21, 33, 10, 82, 2, 89, 29, 32, 75, 60, 37, 96,
    25, 90, 45, 97, 68, 83, 24, 6, 17, 53, 14, 104, 98, 22, 76, 9, 91, 105, 1, 61,
    30, 16, 38, 112, 84, 106, 69, 99, 46, 113, 8, 54, 92, 77, 7, 120, 114, 15, 107, 23,
    62, 121, 31, 100, 85, 39, 70, 122, 115, 47, 93, 108, 78, 55, 123, 101, 63, 116, 86, 71,
    109, 94, 124, 79, 117, 102, 87, 125, 110, 95, 118, 103, 126, 111, 119, 127
);

uint byteAt(int byteOffset) {
    int texelIndex = byteOffset >> 2;
    ivec2 coordinate = ivec2(texelIndex % uDataTexWidth, texelIndex / uDataTexWidth);
    uvec4 texel = texelFetch(uDctData, coordinate, 0);
    int lane = byteOffset & 3;
    return lane == 0 ? texel.r : lane == 1 ? texel.g : lane == 2 ? texel.b : texel.a;
}

uint u32le(int byteOffset) {
    int texelIndex = byteOffset >> 2;
    ivec2 coordinate = ivec2(texelIndex % uDataTexWidth, texelIndex / uDataTexWidth);
    uvec4 bytes = texelFetch(uDctData, coordinate, 0);
    return bytes.r | (bytes.g << 8u) | (bytes.b << 16u) | (bytes.a << 24u);
}

uint readSidecarBits(int byteOffset, int bitOffset, int bitCount) {
    int absoluteBit = (byteOffset << 3) + bitOffset;
    int wordByteOffset = (absoluteBit >> 5) << 2;
    uint wordBit = uint(absoluteBit & 31);
    uint value = u32le(wordByteOffset) >> wordBit;
    if (int(wordBit) + bitCount > 32) {
        value |= u32le(wordByteOffset + 4) << (32u - wordBit);
    }
    return value & ((1u << uint(bitCount)) - 1u);
}

uint componentWordAt(int byteOffset) {
    int texelIndex = byteOffset >> 2;
    ivec2 coordinate = ivec2(texelIndex % uDataTexWidth, texelIndex / uDataTexWidth);
    uvec4 bytes = texelFetch(uDctData, coordinate, 0);
    return (bytes.r << 24u) | (bytes.g << 16u) | (bytes.b << 8u) | bytes.a;
}

uint readComponentBits(int byteOffset, int bitOffset, int bitCount) {
    int absoluteBit = (byteOffset << 3) + bitOffset;
    int wordByteOffset = (absoluteBit >> 5) << 2;
    uint wordBit = uint(absoluteBit & 31);
    uint value = componentWordAt(wordByteOffset) << wordBit;
    if (int(wordBit) + bitCount > 32) {
        value |= componentWordAt(wordByteOffset + 4) >> (32u - wordBit);
    }
    uint mask = (1u << uint(bitCount)) - 1u;
    return (value >> uint(32 - bitCount)) & mask;
}

int readSignedComponentBits(int byteOffset, int bitOffset, int bitCount) {
    uint raw = readComponentBits(byteOffset, bitOffset, bitCount);
    uint sign = 1u << uint(bitCount - 1);
    return (raw & sign) == 0u ? int(raw) : int(raw) - int(1u << uint(bitCount));
}

int ceilDiv(int value, int divisor) {
    return (value + divisor - 1) / divisor;
}

int sidecarBits(int prototypeCount) {
    if (prototypeCount <= 0) return 0;
    int bits = 0;
    int maximumValue = prototypeCount;
    for (int index = 0; index < 6; ++index) {
        if (maximumValue == 0) break;
        bits += 1;
        maximumValue >>= 1;
    }
    return bits;
}

bool headerReferenceVersion(int version) {
    return version >= 2 && version <= 5;
}

bool sidecarReferenceVersion(int version) {
    return version >= 6 && version <= 9;
}

int frequencyQuarters(int version) {
    if (version == 3 || version == 7) return 1;
    if (version == 4 || version == 8) return 2;
    if (version == 5 || version == 9) return 4;
    return 0;
}

int componentWidth(int kind) {
    return kind == 0 ? 16 : 8;
}

int componentHeight(int kind) {
    return kind == 1 ? 8 : 16;
}

int scanLength(int kind) {
    return componentWidth(kind) * componentHeight(kind) - 1;
}

int scanPosition(int kind, int profile, int index) {
    if (kind == 0) return SCAN_Y16[profile * 255 + index];
    if (kind == 1) return SCAN_Y8[profile * 63 + index];
    return SCAN_C[profile * 127 + index];
}

int skipScanPosition(int kind, int profile, int index) {
    if (kind == 0) return SKIP_SCAN_Y16[profile * 255 + index];
    if (kind == 1) return SKIP_SCAN_Y8[profile * 63 + index];
    return SKIP_SCAN_C[profile * 127 + index];
}

int groupCount(int coding) {
    if (coding == 1 || coding == 3 || coding == 4) return 2;
    return coding == 2 || coding == 5 || coding == 6 ? 3 : 0;
}

int mantissaBits(int coding) {
    return coding == 0 ? 6 : 5;
}

int acCount(int recordBytes, int kind, int coding, bool tailReference) {
    int groups = groupCount(coding);
    int count = (recordBytes * 8 - 18 - groups * 3) / mantissaBits(coding);
    return min(scanLength(kind), max(0, count - (tailReference ? 1 : 0)));
}

int resolveLibraryIndex(
    int recordOffset,
    int recordBytes,
    int kind,
    int coding,
    int libraryVersion,
    int sidecarIndex
) {
    int packedProfile = int(byteAt(recordOffset) >> 4u);
    if (headerReferenceVersion(libraryVersion)) return packedProfile >> 2;
    if (sidecarReferenceVersion(libraryVersion)) return sidecarIndex;
    if (libraryVersion == 1) {
        int count = acCount(recordBytes, kind, coding, true);
        int referenceBit = 18 + groupCount(coding) * 3 + count * mantissaBits(coding);
        return int(readComponentBits(recordOffset, referenceBit, mantissaBits(coding)));
    }
    return 0;
}

int groupedScaleIndex(int recordOffset, int coding, int count, int coefficientIndex) {
    if (coding == 0) return int(byteAt(recordOffset) & 15u);
    int group = 0;
    if (coding == 1 || coding == 3 || coding == 4) {
        group = coefficientIndex < count / 2 ? 0 : 1;
    } else {
        int firstEnd = ceilDiv(count, 6);
        int secondEnd = ceilDiv(count, 2);
        group = coefficientIndex < firstEnd ? 0 : coefficientIndex < secondEnd ? 1 : 2;
    }
    return int(readComponentBits(recordOffset, 18 + group * 3, 3));
}

int skipTokenCount(int recordBytes, int kind, int coding) {
    int payloadBits = recordBytes * 8 - 18;
    if (coding == 3) return payloadBits / 8;
    if (recordBytes == 32) return 32;
    if (recordBytes == 24) return 24;
    if (recordBytes == 16) return kind == 0 ? 15 : 14;
    int tokenCount = payloadBits / 7;
    int coarseCount = (tokenCount + 1) / 2;
    if (coarseCount * 8 + (tokenCount - coarseCount) * 6 > payloadBits) tokenCount -= 1;
    return tokenCount;
}

int skipCoarseCount(int recordBytes, int kind, int coding, int tokenCount) {
    if (coding == 3) return tokenCount;
    if (recordBytes == 32) return 16;
    if (recordBytes == 24) return kind == 0 ? 12 : 11;
    if (recordBytes == 16) return kind == 0 ? 7 : 8;
    return (tokenCount + 1) / 2;
}

float basis1D(int frequency, int coordinate, int size) {
    float alpha = frequency == 0 ? sqrt(1.0 / float(size)) : sqrt(2.0 / float(size));
    return alpha * cos(PI * float((2 * coordinate + 1) * frequency) / float(2 * size));
}

float quantizationStep(int position, int kind, int quality) {
    int width = componentWidth(kind);
    int height = componentHeight(kind);
    int u = position % width;
    int v = position / width;
    int tableX = min(7, int(floor(float(u * 7) / float(max(1, width - 1)) + 0.5)));
    int tableY = min(7, int(floor(float(v * 7) / float(max(1, height - 1)) + 0.5)));
    float qualityScale = quality < 50 ? 50.0 / float(quality) : 2.0 - float(quality) * 0.02;
    float dimensionScale = sqrt(float(width * height) / 64.0);
    int tableValue = kind == 2 ? QUANT_C[tableY * 8 + tableX] : QUANT_Y[tableY * 8 + tableX];
    return max(1.0, float(tableValue) * qualityScale * dimensionScale);
}

void addCompensated(float value, inout float sum, inout float correction) {
    float adjusted = value - correction;
    float next = sum + adjusted;
    correction = (next - sum) - adjusted;
    sum = next;
}

int readSignedSidecarBits(int byteOffset, int bitOffset, int bitCount) {
    uint raw = readSidecarBits(byteOffset, bitOffset, bitCount);
    uint sign = 1u << uint(bitCount - 1);
    return (raw & sign) == 0u ? int(raw) : int(raw) - int(1u << uint(bitCount));
}

bool maskedTailPosition(uint maskLow, uint maskHigh, int position) {
    int bit = position - 1;
    return bit < 32 ? ((maskLow >> uint(bit)) & 1u) != 0u :
        ((maskHigh >> uint(bit - 32)) & 1u) != 0u;
}

float sampleMaskedTailRecord(
    int recordOffset,
    int recordBytes,
    int localX,
    int localY,
    int quality
) {
    int dcBits = recordBytes == 24 ? 9 : recordBytes == 32 || recordBytes == 40 ? 8 : 10;
    int acBits = recordBytes == 16 ? 6 : recordBytes == 24 ? 7 : 8;
    int maxAc = recordBytes == 16 ? 9 : recordBytes == 24 ? 17 :
        recordBytes == 32 ? 23 : recordBytes == 40 ? 31 : recordBytes == 48 ? 38 : -1;
    if (maxAc < 0) return 0.0;
    uint maskLow = u32le(recordOffset);
    uint rawMaskHigh = u32le(recordOffset + 4);
    uint maskHigh = rawMaskHigh & 0x3fffffffu;
    int scaleIndex = int(rawMaskHigh >> 30u);
    int explicitCount = bitCount(maskLow) + bitCount(maskHigh);
    if (explicitCount > maxAc) return 0.0;
    int tailCount = maxAc - explicitCount;
    int tailStart = 64 - tailCount;
    for (int position = 1; position <= 62; ++position) {
        if (position >= tailStart && maskedTailPosition(maskLow, maskHigh, position)) return 0.0;
    }

    int bitOffset = 0;
    int dc = readSignedSidecarBits(recordOffset + 8, bitOffset, dcBits);
    bitOffset += dcBits;
    float scale = exp2(float(scaleIndex));
    float sum = 0.0;
    float correction = 0.0;
    addCompensated(
        float(dc) * scale * quantizationStep(0, 1, quality) *
            basis1D(0, localX, 8) * basis1D(0, localY, 8),
        sum,
        correction
    );
    for (int position = 1; position < 64; ++position) {
        bool storedPosition = position >= tailStart ||
            (position <= 62 && maskedTailPosition(maskLow, maskHigh, position));
        if (!storedPosition) continue;
        int stored = readSignedSidecarBits(recordOffset + 8, bitOffset, acBits);
        bitOffset += acBits;
        int u = position & 7;
        int v = position >> 3;
        addCompensated(
            float(stored) * scale * quantizationStep(position, 1, quality) *
                basis1D(u, localX, 8) * basis1D(v, localY, 8),
            sum,
            correction
        );
    }
    return sum;
}

float sampleRecord(
    int recordOffset,
    int recordBytes,
    int kind,
    int localX,
    int localY,
    int quality,
    int coding,
    int libraryVersion,
    int libraryIndex
) {
    if (coding == 6 && kind == 1) {
        return libraryVersion == 0
            ? sampleMaskedTailRecord(recordOffset, recordBytes, localX, localY, quality)
            : 0.0;
    }
    uint header = byteAt(recordOffset);
    int packedProfile = int(header >> 4u);
    int packedScale = int(header & 15u);
    bool skipRecord = coding >= 3 && coding <= 5 && (packedScale & 8) != 0;
    int profile = skipRecord ? packedProfile :
        headerReferenceVersion(libraryVersion) ? packedProfile & 3 : packedProfile;
    int dcScaleIndex = packedScale & 7;
    if (profile < 0 || profile >= (skipRecord ? 8 : 4) ||
        (!skipRecord && packedScale >= 8) || (skipRecord && libraryVersion != 0)) return 0.0;

    int width = componentWidth(kind);
    int height = componentHeight(kind);
    bool tailReference = libraryVersion == 1;
    int count = acCount(recordBytes, kind, coding, tailReference);
    int groups = groupCount(coding);
    int valueBits = mantissaBits(coding);
    int valuesStart = 18 + groups * 3;
    int dc = readSignedComponentBits(recordOffset, 8, 10);
    float sum = 0.0;
    float correction = 0.0;
    addCompensated(
        float(dc) * exp2(float(dcScaleIndex)) * quantizationStep(0, kind, quality) *
            basis1D(0, localX, width) * basis1D(0, localY, height),
        sum,
        correction
    );

    if (skipRecord) {
        int tokenCount = skipTokenCount(recordBytes, kind, coding);
        int coarseCount = skipCoarseCount(recordBytes, kind, coding, tokenCount);
        int bitOffset = 18;
        int scanIndex = 0;
        for (int tokenIndex = 0; tokenIndex < 32; ++tokenIndex) {
            if (tokenIndex >= tokenCount) break;
            if (scanIndex < 0 || scanIndex >= scanLength(kind)) return 0.0;
            bool fine = coding != 3 && tokenIndex >= coarseCount;
            int tokenValueBits = fine ? 4 : 6;
            int scaleIndex = fine ? (dcScaleIndex >= 3 ? 1 : 0) : dcScaleIndex;
            int stored = readSignedComponentBits(recordOffset, bitOffset, tokenValueBits);
            bitOffset += tokenValueBits;
            int skip = int(readComponentBits(recordOffset, bitOffset, 2));
            bitOffset += 2;
            int position = skipScanPosition(kind, profile, scanIndex);
            int u = position % width;
            int v = position / width;
            addCompensated(
                float(stored) * exp2(float(scaleIndex)) * quantizationStep(position, kind, quality) *
                    basis1D(u, localX, width) * basis1D(v, localY, height),
                sum,
                correction
            );
            scanIndex += skip + 1;
        }
        return sum;
    }

    int quarters = libraryIndex > 0 ? frequencyQuarters(libraryVersion) : 0;
    int requestedHigh = (count * quarters + 2) / 4;
    int highCount = min(scanLength(kind) - count, requestedHigh);
    int lowCount = count - highCount;

    for (int index = 0; index < 256; ++index) {
        if (index >= count) break;
        int scanIndex = index < lowCount ? index : count + index - lowCount;
        int position = scanPosition(kind, profile, scanIndex);
        int u = position % width;
        int v = position / width;
        int stored = readSignedComponentBits(recordOffset, valuesStart + index * valueBits, valueBits);
        int scaleIndex = groupedScaleIndex(recordOffset, coding, count, index);
        if (scaleIndex < 0 || scaleIndex >= 8) continue;
        addCompensated(
            float(stored) * exp2(float(scaleIndex)) * quantizationStep(position, kind, quality) *
                basis1D(u, localX, width) * basis1D(v, localY, height),
            sum,
            correction
        );
    }
    return sum;
}

float sampleWithPrototype(
    int recordOffset,
    int recordBytes,
    int prototypeBase,
    int prototypeCount,
    int sidecarIndex,
    int kind,
    int localX,
    int localY,
    int quality,
    int coding,
    int libraryVersion
) {
    int libraryIndex = resolveLibraryIndex(
        recordOffset, recordBytes, kind, coding, libraryVersion, sidecarIndex
    );
    if (libraryIndex < 0 || libraryIndex > prototypeCount) return 128.0;
    float centered = sampleRecord(
        recordOffset, recordBytes, kind, localX, localY, quality, coding,
        libraryVersion, libraryIndex
    );
    if (libraryIndex > 0) {
        int prototypeOffset = prototypeBase + (libraryIndex - 1) * recordBytes;
        centered += sampleRecord(
            prototypeOffset, recordBytes, kind, localX, localY, quality, coding, 0, 0
        );
    }
    return centered + 128.0;
}

int readSidecarReference(int referenceBase, int referenceBits, int referenceIndex) {
    return referenceBits == 0 ? 0 : int(readSidecarBits(
        referenceBase, referenceIndex * referenceBits, referenceBits
    ));
}

ivec2 imageSizeFromHeader() {
    return ivec2(int(u32le(16)), int(u32le(20)));
}

ivec2 uvToPixel(ivec2 imageSize) {
    vec2 uv = clamp(vTexCoord, vec2(0.0), vec2(0.99999994));
    ivec2 pixel = ivec2(floor(uv * vec2(imageSize)));
    if (uFlipY) pixel.y = imageSize.y - 1 - pixel.y;
    return clamp(pixel, ivec2(0), imageSize - 1);
}

vec3 yCbCrToRgb(float y, float cb, float cr) {
    cb -= 128.0;
    cr -= 128.0;
    vec3 rgb = vec3(
        y + 1.402 * cr,
        y - 0.344136 * cb - 0.714136 * cr,
        y + 1.772 * cb
    );
    return clamp(rgb / 255.0, 0.0, 1.0);
}

bool validMainHeader(uint flags) {
    return u32le(0) == 0x42544344u && u32le(4) == 0x00003253u &&
        u32le(8) == 2u && u32le(12) == EXPECTED_MODE &&
        u32le(32) == EXPECTED_MCU_BYTES && u32le(36) == EXPECTED_Y_BYTES &&
        u32le(40) == EXPECTED_CB_BYTES && u32le(44) == EXPECTED_CR_BYTES &&
        (flags & ~0x00000f07u) == 0u && ((flags >> 8u) & 15u) <= 6u &&
        (((flags & FLAG_LIBRARY) == 0u) || ((flags >> 8u) & 15u) != 6u) &&
        (ALLOW_SPLIT_LUMA || (flags & FLAG_SPLIT_LUMA) == 0u);
}

void main() {
    uint flags = u32le(52);
    if (!validMainHeader(flags)) {
        outColor = vec4(1.0, 0.0, 1.0, 1.0);
        return;
    }

    ivec2 size = imageSizeFromHeader();
    ivec2 pixel = uvToPixel(size);
    int mcuColumns = int(u32le(24));
    int mcuRows = int(u32le(28));
    int mcuCount = mcuColumns * mcuRows;
    int mcuIndex = (pixel.y >> 4) * mcuColumns + (pixel.x >> 4);
    int mcuOffset = HEADER_SIZE + mcuIndex * int(EXPECTED_MCU_BYTES);
    int quality = int(u32le(48));
    int coding = int((flags >> 8u) & 15u);
    bool splitLuma = (flags & FLAG_SPLIT_LUMA) != 0u;

    int libraryVersion = 0;
    int yPrototypeCount = 0;
    int cbPrototypeCount = 0;
    int crPrototypeCount = 0;
    int yReferenceBase = 0;
    int cbReferenceBase = 0;
    int crReferenceBase = 0;
    int yReferenceBits = 0;
    int cbReferenceBits = 0;
    int crReferenceBits = 0;
    int yPrototypeBase = 0;
    int cbPrototypeBase = 0;
    int crPrototypeBase = 0;

    if ((flags & FLAG_LIBRARY) != 0u) {
        int libraryBase = HEADER_SIZE + int(u32le(56));
        if (u32le(libraryBase) != 0x4c544344u ||
            u32le(libraryBase + 4) != 0x00314249u) {
            outColor = vec4(1.0, 0.0, 1.0, 1.0);
            return;
        }
        libraryVersion = int(u32le(libraryBase + 8));
        yPrototypeCount = int(u32le(libraryBase + 12));
        cbPrototypeCount = int(u32le(libraryBase + 16));
        crPrototypeCount = int(u32le(libraryBase + 20));
        bool sidecar = sidecarReferenceVersion(libraryVersion);
        yReferenceBits = sidecar ? sidecarBits(yPrototypeCount) : 0;
        cbReferenceBits = sidecar ? sidecarBits(cbPrototypeCount) : 0;
        crReferenceBits = sidecar ? sidecarBits(crPrototypeCount) : 0;
        int yReferenceCount = mcuCount * (splitLuma ? 4 : 1);
        int yReferenceBytes = ceilDiv(yReferenceCount * yReferenceBits, 8);
        int cbReferenceBytes = ceilDiv(mcuCount * cbReferenceBits, 8);
        int crReferenceBytes = ceilDiv(mcuCount * crReferenceBits, 8);
        yReferenceBase = libraryBase + LIBRARY_HEADER_SIZE;
        cbReferenceBase = yReferenceBase + yReferenceBytes;
        crReferenceBase = cbReferenceBase + cbReferenceBytes;
        yPrototypeBase = crReferenceBase + crReferenceBytes;
        int yRecordBytes = splitLuma ? int(EXPECTED_Y_BYTES) / 4 : int(EXPECTED_Y_BYTES);
        cbPrototypeBase = yPrototypeBase + yPrototypeCount * yRecordBytes;
        crPrototypeBase = cbPrototypeBase + cbPrototypeCount * int(EXPECTED_CB_BYTES);
    }

    ivec2 local = pixel & 15;
    int yRecordOffset = mcuOffset;
    int yRecordBytes = int(EXPECTED_Y_BYTES);
    int yKind = 0;
    int yReferenceOrdinal = mcuIndex;
    ivec2 yLocal = local;
    if (splitLuma) {
        int block = (local.y >> 3) * 2 + (local.x >> 3);
        yRecordBytes /= 4;
        yRecordOffset += block * yRecordBytes;
        yKind = 1;
        yReferenceOrdinal = mcuIndex * 4 + block;
        yLocal &= 7;
    }
    int ySidecarIndex = readSidecarReference(
        yReferenceBase, yReferenceBits, yReferenceOrdinal
    );
    int cbSidecarIndex = readSidecarReference(
        cbReferenceBase, cbReferenceBits, mcuIndex
    );
    int crSidecarIndex = readSidecarReference(
        crReferenceBase, crReferenceBits, mcuIndex
    );

    float y = sampleWithPrototype(
        yRecordOffset, yRecordBytes, yPrototypeBase, yPrototypeCount, ySidecarIndex,
        yKind, yLocal.x, yLocal.y, quality, coding, libraryVersion
    );
    float cb = sampleWithPrototype(
        mcuOffset + int(EXPECTED_Y_BYTES), int(EXPECTED_CB_BYTES),
        cbPrototypeBase, cbPrototypeCount, cbSidecarIndex,
        2, local.x >> 1, local.y, quality, coding, libraryVersion
    );
    float cr = sampleWithPrototype(
        mcuOffset + int(EXPECTED_Y_BYTES + EXPECTED_CB_BYTES), int(EXPECTED_CR_BYTES),
        crPrototypeBase, crPrototypeCount, crSidecarIndex,
        2, local.x >> 1, local.y, quality, coding, libraryVersion
    );
    outColor = vec4(yCbCrToRgb(y, cb, cr), 1.0);
}
