#version 300 es
precision highp float;
precision highp int;
precision highp usampler2D;

// Generated by tools/generate-dctbs2-shaders.js.
// Direct random-access decoder for the current 64-byte-header DCTBS2 v2 format.
uniform highp usampler2D uDctData;
uniform int uDataTexWidth;
uniform bool uFlipY;

in vec2 vTexCoord;
out vec4 outColor;

const float PI = 3.1415926535897932384626433832795;
const int HEADER_SIZE = 64;
const int LIBRARY_HEADER_SIZE = 32;
const uint EXPECTED_MODE = 4500u;
const uint EXPECTED_MCU_BYTES = 144u;
const uint EXPECTED_Y_BYTES = 96u;
const uint EXPECTED_CB_BYTES = 24u;
const uint EXPECTED_CR_BYTES = 24u;
const bool ALLOW_SPLIT_LUMA = true;
const uint FLAG_SPLIT_LUMA = 2u;
const uint FLAG_LIBRARY = 4u;

const int QUANT_Y[64] = int[64](
    16, 11, 10, 16, 24, 40, 51, 61, 12, 12, 14, 19, 26, 58, 60, 55, 14, 13, 16, 24,
    40, 57, 69, 56, 14, 17, 22, 29, 51, 87, 80, 62, 18, 22, 37, 56, 68, 109, 103, 77,
    24, 35, 55, 64, 81, 104, 113, 92, 49, 64, 78, 87, 103, 121, 120, 101, 72, 92, 95, 98,
    112, 100, 103, 99
);

const int QUANT_C[64] = int[64](
    17, 18, 24, 47, 99, 99, 99, 99, 18, 21, 26, 66, 99, 99, 99, 99, 24, 26, 56, 99,
    99, 99, 99, 99, 47, 66, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
    99, 99, 99, 99
);

const int SCAN_Y16[1020] = int[1020](
    16, 1, 2, 17, 32, 48, 33, 18, 3, 4, 19, 34, 49, 64, 80, 65, 50, 35, 20, 5,
    6, 21, 36, 51, 66, 81, 96, 112, 97, 82, 67, 52, 37, 22, 7, 8, 23, 38, 53, 68,
    83, 98, 113, 128, 144, 129, 114, 99, 84, 69, 54, 39, 24, 9, 10, 25, 40, 55, 70, 85,
    100, 115, 130, 145, 160, 176, 161, 146, 131, 116, 101, 86, 71, 56, 41, 26, 11, 12, 27, 42,
    57, 72, 87, 102, 117, 132, 147, 162, 177, 192, 208, 193, 178, 163, 148, 133, 118, 103, 88, 73,
    58, 43, 28, 13, 14, 29, 44, 59, 74, 89, 104, 119, 134, 149, 164, 179, 194, 209, 224, 240,
    225, 210, 195, 180, 165, 150, 135, 120, 105, 90, 75, 60, 45, 30, 15, 31, 46, 61, 76, 91,
    106, 121, 136, 151, 166, 181, 196, 211, 226, 241, 242, 227, 212, 197, 182, 167, 152, 137, 122, 107,
    92, 77, 62, 47, 63, 78, 93, 108, 123, 138, 153, 168, 183, 198, 213, 228, 243, 244, 229, 214,
    199, 184, 169, 154, 139, 124, 109, 94, 79, 95, 110, 125, 140, 155, 170, 185, 200, 215, 230, 245,
    246, 231, 216, 201, 186, 171, 156, 141, 126, 111, 127, 142, 157, 172, 187, 202, 217, 232, 247, 248,
    233, 218, 203, 188, 173, 158, 143, 159, 174, 189, 204, 219, 234, 249, 250, 235, 220, 205, 190, 175,
    191, 206, 221, 236, 251, 252, 237, 222, 207, 223, 238, 253, 254, 239, 255, 1, 2, 16, 3, 17,
    4, 18, 32, 5, 19, 33, 6, 20, 34, 7, 48, 21, 35, 8, 49, 22, 36, 9, 50, 23,
    64, 37, 10, 51, 24, 65, 38, 11, 52, 25, 66, 39, 80, 12, 53, 26, 67, 40, 81, 13,
    54, 27, 68, 41, 82, 14, 55, 96, 28, 69, 42, 83, 15, 56, 97, 29, 70, 43, 84, 57,
    98, 30, 71, 112, 44, 85, 58, 99, 31, 72, 113, 45, 86, 59, 100, 73, 114, 46, 87, 128,
    60, 101, 74, 115, 47, 88, 129, 61, 102, 75, 116, 89, 130, 62, 103, 144, 76, 117, 90, 131,
    63, 104, 145, 77, 118, 91, 132, 105, 146, 78, 119, 160, 92, 133, 106, 147, 79, 120, 161, 93,
    134, 107, 148, 121, 162, 94, 135, 176, 108, 149, 122, 163, 95, 136, 177, 109, 150, 123, 164, 137,
    178, 110, 151, 192, 124, 165, 138, 179, 111, 152, 193, 125, 166, 139, 180, 153, 194, 126, 167, 208,
    140, 181, 154, 195, 127, 168, 209, 141, 182, 155, 196, 169, 210, 142, 183, 156, 224, 197, 170, 211,
    143, 184, 157, 225, 198, 171, 212, 185, 158, 226, 199, 240, 172, 213, 186, 159, 227, 200, 241, 173,
    214, 187, 228, 201, 242, 174, 215, 188, 229, 202, 243, 175, 216, 189, 230, 203, 244, 217, 190, 231,
    204, 245, 218, 191, 232, 205, 246, 219, 233, 206, 247, 220, 234, 207, 248, 221, 235, 249, 222, 236,
    250, 223, 237, 251, 238, 252, 239, 253, 254, 255, 16, 32, 1, 48, 17, 64, 33, 2, 80, 49,
    18, 96, 65, 34, 112, 3, 81, 50, 128, 19, 97, 66, 144, 35, 113, 4, 82, 160, 51, 129,
    20, 98, 176, 67, 145, 36, 114, 5, 192, 83, 161, 52, 130, 21, 208, 99, 177, 68, 146, 37,
    224, 115, 6, 193, 84, 162, 53, 240, 131, 22, 209, 100, 178, 69, 147, 38, 225, 116, 7, 194,
    85, 163, 54, 241, 132, 23, 210, 101, 179, 70, 148, 39, 226, 117, 8, 195, 86, 164, 55, 242,
    133, 24, 211, 102, 180, 71, 149, 40, 227, 118, 9, 196, 87, 165, 56, 243, 134, 25, 212, 103,
    181, 72, 150, 41, 228, 119, 10, 197, 88, 166, 57, 244, 135, 26, 213, 104, 182, 73, 151, 42,
    229, 120, 11, 198, 89, 167, 58, 245, 136, 27, 214, 105, 183, 74, 152, 43, 230, 121, 12, 199,
    90, 168, 59, 246, 137, 28, 215, 106, 184, 75, 153, 44, 231, 122, 13, 200, 91, 169, 60, 247,
    138, 29, 216, 107, 185, 76, 154, 45, 232, 123, 201, 14, 92, 170, 61, 248, 139, 217, 30, 108,
    186, 77, 155, 233, 46, 124, 15, 202, 93, 171, 249, 62, 140, 31, 218, 109, 187, 78, 156, 47,
    234, 125, 203, 94, 172, 63, 250, 141, 219, 110, 188, 79, 157, 235, 126, 204, 95, 173, 251, 142,
    220, 111, 189, 158, 236, 127, 205, 174, 252, 143, 221, 190, 159, 237, 206, 175, 253, 222, 191, 238,
    207, 254, 223, 239, 255, 17, 1, 16, 34, 18, 33, 2, 32, 51, 35, 50, 19, 49, 3, 48,
    68, 52, 67, 36, 66, 20, 65, 4, 64, 85, 69, 84, 53, 83, 37, 82, 21, 81, 5, 80,
    102, 86, 101, 70, 100, 54, 99, 38, 98, 22, 97, 6, 96, 119, 103, 118, 87, 117, 71, 116,
    55, 115, 39, 114, 23, 113, 7, 112, 136, 120, 135, 104, 134, 88, 133, 72, 132, 56, 131, 40,
    130, 24, 129, 8, 128, 153, 137, 152, 121, 151, 105, 150, 89, 149, 73, 148, 57, 147, 41, 146,
    25, 145, 9, 144, 170, 154, 169, 138, 168, 122, 167, 106, 166, 90, 165, 74, 164, 58, 163, 42,
    162, 26, 161, 10, 160, 187, 171, 186, 155, 185, 139, 184, 123, 183, 107, 182, 91, 181, 75, 180,
    59, 179, 43, 178, 27, 177, 11, 176, 204, 188, 203, 172, 202, 156, 201, 140, 200, 124, 199, 108,
    198, 92, 197, 76, 196, 60, 195, 44, 194, 28, 193, 12, 192, 221, 205, 220, 189, 219, 173, 218,
    157, 217, 141, 216, 125, 215, 109, 214, 93, 213, 77, 212, 61, 211, 45, 210, 29, 209, 13, 208,
    238, 222, 237, 206, 236, 190, 235, 174, 234, 158, 233, 142, 232, 126, 231, 110, 230, 94, 229, 78,
    228, 62, 227, 46, 226, 30, 225, 14, 224, 255, 239, 254, 223, 253, 207, 252, 191, 251, 175, 250,
    159, 249, 143, 248, 127, 247, 111, 246, 95, 245, 79, 244, 63, 243, 47, 242, 31, 241, 15, 240
);

const int SCAN_Y8[252] = int[252](
    8, 1, 2, 9, 16, 24, 17, 10, 3, 4, 11, 18, 25, 32, 40, 33, 26, 19, 12, 5,
    6, 13, 20, 27, 34, 41, 48, 56, 49, 42, 35, 28, 21, 14, 7, 15, 22, 29, 36, 43,
    50, 57, 58, 51, 44, 37, 30, 23, 31, 38, 45, 52, 59, 60, 53, 46, 39, 47, 54, 61,
    62, 55, 63, 1, 2, 8, 3, 9, 4, 10, 16, 5, 11, 17, 6, 12, 18, 7, 24, 13,
    19, 25, 14, 20, 26, 15, 32, 21, 27, 33, 22, 28, 34, 23, 40, 29, 35, 41, 30, 36,
    42, 31, 48, 37, 43, 49, 38, 44, 50, 39, 56, 45, 51, 57, 46, 52, 58, 47, 53, 59,
    54, 60, 55, 61, 62, 63, 8, 16, 1, 24, 9, 32, 17, 2, 40, 25, 10, 48, 33, 18,
    56, 3, 41, 26, 11, 49, 34, 19, 57, 4, 42, 27, 12, 50, 35, 20, 58, 5, 43, 28,
    13, 51, 36, 21, 59, 6, 44, 29, 14, 52, 37, 22, 60, 7, 45, 30, 15, 53, 38, 23,
    61, 46, 31, 54, 39, 62, 47, 55, 63, 9, 1, 8, 18, 10, 17, 2, 16, 27, 19, 26,
    11, 25, 3, 24, 36, 28, 35, 20, 34, 12, 33, 4, 32, 45, 37, 44, 29, 43, 21, 42,
    13, 41, 5, 40, 54, 46, 53, 38, 52, 30, 51, 22, 50, 14, 49, 6, 48, 63, 55, 62,
    47, 61, 39, 60, 31, 59, 23, 58, 15, 57, 7, 56
);

const int SCAN_C[508] = int[508](
    8, 1, 2, 9, 16, 24, 17, 10, 3, 4, 11, 18, 25, 32, 40, 33, 26, 19, 12, 5,
    6, 13, 20, 27, 34, 41, 48, 56, 49, 42, 35, 28, 21, 14, 7, 15, 22, 29, 36, 43,
    50, 57, 64, 72, 65, 58, 51, 44, 37, 30, 23, 31, 38, 45, 52, 59, 66, 73, 80, 88,
    81, 74, 67, 60, 53, 46, 39, 47, 54, 61, 68, 75, 82, 89, 96, 104, 97, 90, 83, 76,
    69, 62, 55, 63, 70, 77, 84, 91, 98, 105, 112, 120, 113, 106, 99, 92, 85, 78, 71, 79,
    86, 93, 100, 107, 114, 121, 122, 115, 108, 101, 94, 87, 95, 102, 109, 116, 123, 124, 117, 110,
    103, 111, 118, 125, 126, 119, 127, 1, 2, 8, 3, 9, 4, 10, 16, 5, 11, 17, 6, 12,
    18, 7, 24, 13, 19, 25, 14, 20, 26, 15, 32, 21, 27, 33, 22, 28, 34, 23, 40, 29,
    35, 41, 30, 36, 42, 31, 48, 37, 43, 49, 38, 44, 50, 39, 56, 45, 51, 57, 46, 52,
    58, 47, 64, 53, 59, 65, 54, 60, 66, 55, 72, 61, 67, 73, 62, 68, 74, 63, 80, 69,
    75, 81, 70, 76, 82, 71, 88, 77, 83, 89, 78, 84, 90, 79, 96, 85, 91, 97, 86, 92,
    98, 87, 104, 93, 99, 105, 94, 100, 106, 95, 112, 101, 107, 113, 102, 108, 114, 103, 120, 109,
    115, 121, 110, 116, 122, 111, 117, 123, 118, 124, 119, 125, 126, 127, 8, 16, 1, 24, 9, 32,
    17, 2, 40, 25, 10, 48, 33, 18, 56, 3, 41, 26, 64, 11, 49, 34, 72, 19, 57, 4,
    42, 80, 27, 65, 12, 50, 88, 35, 73, 20, 58, 5, 96, 43, 81, 28, 66, 13, 104, 51,
    89, 36, 74, 21, 112, 59, 6, 97, 44, 82, 29, 120, 67, 14, 105, 52, 90, 37, 75, 22,
    113, 60, 7, 98, 45, 83, 30, 121, 68, 15, 106, 53, 91, 38, 76, 23, 114, 61, 99, 46,
    84, 31, 122, 69, 107, 54, 92, 39, 77, 115, 62, 100, 47, 85, 123, 70, 108, 55, 93, 78,
    116, 63, 101, 86, 124, 71, 109, 94, 79, 117, 102, 87, 125, 110, 95, 118, 103, 126, 111, 119,
    127, 9, 1, 8, 18, 10, 17, 2, 16, 27, 19, 26, 11, 25, 3, 24, 36, 28, 35, 20,
    34, 12, 33, 4, 32, 45, 37, 44, 29, 43, 21, 42, 13, 41, 5, 40, 54, 46, 53, 38,
    52, 30, 51, 22, 50, 14, 49, 6, 48, 63, 55, 62, 47, 61, 39, 60, 31, 59, 23, 58,
    15, 57, 7, 56, 71, 70, 69, 68, 67, 66, 65, 64, 79, 78, 77, 76, 75, 74, 73, 72,
    87, 86, 85, 84, 83, 82, 81, 80, 95, 94, 93, 92, 91, 90, 89, 88, 103, 102, 101, 100,
    99, 98, 97, 96, 111, 110, 109, 108, 107, 106, 105, 104, 119, 118, 117, 116, 115, 114, 113, 112,
    127, 126, 125, 124, 123, 122, 121, 120
);

uint byteAt(int byteOffset) {
    int texelIndex = byteOffset >> 2;
    ivec2 coordinate = ivec2(texelIndex % uDataTexWidth, texelIndex / uDataTexWidth);
    uvec4 texel = texelFetch(uDctData, coordinate, 0);
    int lane = byteOffset & 3;
    return lane == 0 ? texel.r : lane == 1 ? texel.g : lane == 2 ? texel.b : texel.a;
}

uint u32le(int byteOffset) {
    return byteAt(byteOffset) |
        (byteAt(byteOffset + 1) << 8u) |
        (byteAt(byteOffset + 2) << 16u) |
        (byteAt(byteOffset + 3) << 24u);
}

uint readSidecarBits(int byteOffset, int bitOffset, int bitCount) {
    uint value = 0u;
    for (int bit = 0; bit < 16; ++bit) {
        if (bit >= bitCount) break;
        int absoluteBit = bitOffset + bit;
        uint source = byteAt(byteOffset + (absoluteBit >> 3));
        value |= ((source >> uint(absoluteBit & 7)) & 1u) << uint(bit);
    }
    return value;
}

uint readComponentBits(int byteOffset, int bitOffset, int bitCount) {
    uint value = 0u;
    for (int bit = 0; bit < 16; ++bit) {
        if (bit >= bitCount) break;
        int absoluteBit = bitOffset + bit;
        uint source = byteAt(byteOffset + (absoluteBit >> 3));
        value = value * 2u + ((source >> uint(7 - (absoluteBit & 7))) & 1u);
    }
    return value;
}

int readSignedComponentBits(int byteOffset, int bitOffset, int bitCount) {
    uint raw = readComponentBits(byteOffset, bitOffset, bitCount);
    uint sign = 1u << uint(bitCount - 1);
    return (raw & sign) == 0u ? int(raw) : int(raw) - int(1u << uint(bitCount));
}

int ceilDiv(int value, int divisor) {
    return (value + divisor - 1) / divisor;
}

int sidecarBits(int prototypeCount) {
    if (prototypeCount <= 0) return 0;
    int bits = 0;
    int maximumValue = prototypeCount;
    for (int index = 0; index < 6; ++index) {
        if (maximumValue == 0) break;
        bits += 1;
        maximumValue >>= 1;
    }
    return bits;
}

bool headerReferenceVersion(int version) {
    return version >= 2 && version <= 5;
}

bool sidecarReferenceVersion(int version) {
    return version >= 6 && version <= 9;
}

int frequencyQuarters(int version) {
    if (version == 3 || version == 7) return 1;
    if (version == 4 || version == 8) return 2;
    if (version == 5 || version == 9) return 4;
    return 0;
}

int componentWidth(int kind) {
    return kind == 0 ? 16 : 8;
}

int componentHeight(int kind) {
    return kind == 1 ? 8 : 16;
}

int scanLength(int kind) {
    return componentWidth(kind) * componentHeight(kind) - 1;
}

int scanPosition(int kind, int profile, int index) {
    if (kind == 0) return SCAN_Y16[profile * 255 + index];
    if (kind == 1) return SCAN_Y8[profile * 63 + index];
    return SCAN_C[profile * 127 + index];
}

int groupCount(int coding) {
    return coding == 1 ? 2 : coding == 2 ? 3 : 0;
}

int mantissaBits(int coding) {
    return coding == 0 ? 6 : 5;
}

int acCount(int recordBytes, int coding, bool tailReference) {
    int groups = groupCount(coding);
    int count = (recordBytes * 8 - 18 - groups * 3) / mantissaBits(coding);
    return max(0, count - (tailReference ? 1 : 0));
}

int resolveLibraryIndex(
    int recordOffset,
    int recordBytes,
    int coding,
    int libraryVersion,
    int sidecarIndex
) {
    int packedProfile = int(byteAt(recordOffset) >> 4u);
    if (headerReferenceVersion(libraryVersion)) return packedProfile >> 2;
    if (sidecarReferenceVersion(libraryVersion)) return sidecarIndex;
    if (libraryVersion == 1) {
        int count = acCount(recordBytes, coding, true);
        int referenceBit = 18 + groupCount(coding) * 3 + count * mantissaBits(coding);
        return int(readComponentBits(recordOffset, referenceBit, mantissaBits(coding)));
    }
    return 0;
}

int groupedScaleIndex(int recordOffset, int coding, int count, int coefficientIndex) {
    if (coding == 0) return int(byteAt(recordOffset) & 15u);
    int group = 0;
    if (coding == 1) {
        group = coefficientIndex < count / 2 ? 0 : 1;
    } else {
        int firstEnd = ceilDiv(count, 6);
        int secondEnd = ceilDiv(count, 2);
        group = coefficientIndex < firstEnd ? 0 : coefficientIndex < secondEnd ? 1 : 2;
    }
    return int(readComponentBits(recordOffset, 18 + group * 3, 3));
}

float basis1D(int frequency, int coordinate, int size) {
    float alpha = frequency == 0 ? sqrt(1.0 / float(size)) : sqrt(2.0 / float(size));
    return alpha * cos(PI * float((2 * coordinate + 1) * frequency) / float(2 * size));
}

float quantizationStep(int position, int kind, int quality) {
    int width = componentWidth(kind);
    int height = componentHeight(kind);
    int u = position % width;
    int v = position / width;
    int tableX = min(7, int(floor(float(u * 7) / float(max(1, width - 1)) + 0.5)));
    int tableY = min(7, int(floor(float(v * 7) / float(max(1, height - 1)) + 0.5)));
    float qualityScale = quality < 50 ? 50.0 / float(quality) : 2.0 - float(quality) * 0.02;
    float dimensionScale = sqrt(float(width * height) / 64.0);
    int tableValue = kind == 2 ? QUANT_C[tableY * 8 + tableX] : QUANT_Y[tableY * 8 + tableX];
    return max(1.0, float(tableValue) * qualityScale * dimensionScale);
}

void addCompensated(float value, inout float sum, inout float correction) {
    float adjusted = value - correction;
    float next = sum + adjusted;
    correction = (next - sum) - adjusted;
    sum = next;
}

float sampleRecord(
    int recordOffset,
    int recordBytes,
    int kind,
    int localX,
    int localY,
    int quality,
    int coding,
    int libraryVersion,
    int libraryIndex
) {
    int packedProfile = int(byteAt(recordOffset) >> 4u);
    int profile = headerReferenceVersion(libraryVersion) ? packedProfile & 3 : packedProfile;
    int dcScaleIndex = int(byteAt(recordOffset) & 15u);
    if (profile < 0 || profile >= 4 || dcScaleIndex < 0 || dcScaleIndex >= 8) return 0.0;

    int width = componentWidth(kind);
    int height = componentHeight(kind);
    bool tailReference = libraryVersion == 1;
    int count = acCount(recordBytes, coding, tailReference);
    int groups = groupCount(coding);
    int valueBits = mantissaBits(coding);
    int valuesStart = 18 + groups * 3;
    int dc = readSignedComponentBits(recordOffset, 8, 10);
    float sum = 0.0;
    float correction = 0.0;
    addCompensated(
        float(dc) * exp2(float(dcScaleIndex)) * quantizationStep(0, kind, quality) *
            basis1D(0, localX, width) * basis1D(0, localY, height),
        sum,
        correction
    );

    int quarters = libraryIndex > 0 ? frequencyQuarters(libraryVersion) : 0;
    int requestedHigh = (count * quarters + 2) / 4;
    int highCount = min(scanLength(kind) - count, requestedHigh);
    int lowCount = count - highCount;

    for (int index = 0; index < 256; ++index) {
        if (index >= count) break;
        int scanIndex = index < lowCount ? index : count + index - lowCount;
        int position = scanPosition(kind, profile, scanIndex);
        int u = position % width;
        int v = position / width;
        int stored = readSignedComponentBits(recordOffset, valuesStart + index * valueBits, valueBits);
        int scaleIndex = groupedScaleIndex(recordOffset, coding, count, index);
        if (scaleIndex < 0 || scaleIndex >= 8) continue;
        addCompensated(
            float(stored) * exp2(float(scaleIndex)) * quantizationStep(position, kind, quality) *
                basis1D(u, localX, width) * basis1D(v, localY, height),
            sum,
            correction
        );
    }
    return sum;
}

float sampleWithPrototype(
    int recordOffset,
    int recordBytes,
    int prototypeBase,
    int prototypeCount,
    int sidecarIndex,
    int kind,
    int localX,
    int localY,
    int quality,
    int coding,
    int libraryVersion
) {
    int libraryIndex = resolveLibraryIndex(
        recordOffset, recordBytes, coding, libraryVersion, sidecarIndex
    );
    if (libraryIndex < 0 || libraryIndex > prototypeCount) return 128.0;
    float centered = sampleRecord(
        recordOffset, recordBytes, kind, localX, localY, quality, coding,
        libraryVersion, libraryIndex
    );
    if (libraryIndex > 0) {
        int prototypeOffset = prototypeBase + (libraryIndex - 1) * recordBytes;
        centered += sampleRecord(
            prototypeOffset, recordBytes, kind, localX, localY, quality, coding, 0, 0
        );
    }
    return centered + 128.0;
}

int readSidecarReference(int referenceBase, int referenceBits, int referenceIndex) {
    return referenceBits == 0 ? 0 : int(readSidecarBits(
        referenceBase, referenceIndex * referenceBits, referenceBits
    ));
}

ivec2 imageSizeFromHeader() {
    return ivec2(int(u32le(16)), int(u32le(20)));
}

ivec2 uvToPixel(ivec2 imageSize) {
    vec2 uv = clamp(vTexCoord, vec2(0.0), vec2(0.99999994));
    ivec2 pixel = ivec2(floor(uv * vec2(imageSize)));
    if (uFlipY) pixel.y = imageSize.y - 1 - pixel.y;
    return clamp(pixel, ivec2(0), imageSize - 1);
}

vec3 yCbCrToRgb(float y, float cb, float cr) {
    cb -= 128.0;
    cr -= 128.0;
    vec3 rgb = vec3(
        y + 1.402 * cr,
        y - 0.344136 * cb - 0.714136 * cr,
        y + 1.772 * cb
    );
    return clamp(rgb / 255.0, 0.0, 1.0);
}

bool validMainHeader(uint flags) {
    return u32le(0) == 0x42544344u && u32le(4) == 0x00003253u &&
        u32le(8) == 2u && u32le(12) == EXPECTED_MODE &&
        u32le(32) == EXPECTED_MCU_BYTES && u32le(36) == EXPECTED_Y_BYTES &&
        u32le(40) == EXPECTED_CB_BYTES && u32le(44) == EXPECTED_CR_BYTES &&
        (flags & ~0x00000f07u) == 0u && ((flags >> 8u) & 15u) <= 2u &&
        (ALLOW_SPLIT_LUMA || (flags & FLAG_SPLIT_LUMA) == 0u);
}

void main() {
    uint flags = u32le(52);
    if (!validMainHeader(flags)) {
        outColor = vec4(1.0, 0.0, 1.0, 1.0);
        return;
    }

    ivec2 size = imageSizeFromHeader();
    ivec2 pixel = uvToPixel(size);
    int mcuColumns = int(u32le(24));
    int mcuRows = int(u32le(28));
    int mcuCount = mcuColumns * mcuRows;
    int mcuIndex = (pixel.y >> 4) * mcuColumns + (pixel.x >> 4);
    int mcuOffset = HEADER_SIZE + mcuIndex * int(EXPECTED_MCU_BYTES);
    int quality = int(u32le(48));
    int coding = int((flags >> 8u) & 15u);
    bool splitLuma = (flags & FLAG_SPLIT_LUMA) != 0u;

    int libraryVersion = 0;
    int yPrototypeCount = 0;
    int cbPrototypeCount = 0;
    int crPrototypeCount = 0;
    int yReferenceBase = 0;
    int cbReferenceBase = 0;
    int crReferenceBase = 0;
    int yReferenceBits = 0;
    int cbReferenceBits = 0;
    int crReferenceBits = 0;
    int yPrototypeBase = 0;
    int cbPrototypeBase = 0;
    int crPrototypeBase = 0;

    if ((flags & FLAG_LIBRARY) != 0u) {
        int libraryBase = HEADER_SIZE + int(u32le(56));
        if (u32le(libraryBase) != 0x4c544344u ||
            u32le(libraryBase + 4) != 0x00314249u) {
            outColor = vec4(1.0, 0.0, 1.0, 1.0);
            return;
        }
        libraryVersion = int(u32le(libraryBase + 8));
        yPrototypeCount = int(u32le(libraryBase + 12));
        cbPrototypeCount = int(u32le(libraryBase + 16));
        crPrototypeCount = int(u32le(libraryBase + 20));
        bool sidecar = sidecarReferenceVersion(libraryVersion);
        yReferenceBits = sidecar ? sidecarBits(yPrototypeCount) : 0;
        cbReferenceBits = sidecar ? sidecarBits(cbPrototypeCount) : 0;
        crReferenceBits = sidecar ? sidecarBits(crPrototypeCount) : 0;
        int yReferenceCount = mcuCount * (splitLuma ? 4 : 1);
        int yReferenceBytes = ceilDiv(yReferenceCount * yReferenceBits, 8);
        int cbReferenceBytes = ceilDiv(mcuCount * cbReferenceBits, 8);
        int crReferenceBytes = ceilDiv(mcuCount * crReferenceBits, 8);
        yReferenceBase = libraryBase + LIBRARY_HEADER_SIZE;
        cbReferenceBase = yReferenceBase + yReferenceBytes;
        crReferenceBase = cbReferenceBase + cbReferenceBytes;
        yPrototypeBase = crReferenceBase + crReferenceBytes;
        int yRecordBytes = splitLuma ? int(EXPECTED_Y_BYTES) / 4 : int(EXPECTED_Y_BYTES);
        cbPrototypeBase = yPrototypeBase + yPrototypeCount * yRecordBytes;
        crPrototypeBase = cbPrototypeBase + cbPrototypeCount * int(EXPECTED_CB_BYTES);
    }

    ivec2 local = pixel & 15;
    int yRecordOffset = mcuOffset;
    int yRecordBytes = int(EXPECTED_Y_BYTES);
    int yKind = 0;
    int yReferenceOrdinal = mcuIndex;
    ivec2 yLocal = local;
    if (splitLuma) {
        int block = (local.y >> 3) * 2 + (local.x >> 3);
        yRecordBytes /= 4;
        yRecordOffset += block * yRecordBytes;
        yKind = 1;
        yReferenceOrdinal = mcuIndex * 4 + block;
        yLocal &= 7;
    }
    int ySidecarIndex = readSidecarReference(
        yReferenceBase, yReferenceBits, yReferenceOrdinal
    );
    int cbSidecarIndex = readSidecarReference(
        cbReferenceBase, cbReferenceBits, mcuIndex
    );
    int crSidecarIndex = readSidecarReference(
        crReferenceBase, crReferenceBits, mcuIndex
    );

    float y = sampleWithPrototype(
        yRecordOffset, yRecordBytes, yPrototypeBase, yPrototypeCount, ySidecarIndex,
        yKind, yLocal.x, yLocal.y, quality, coding, libraryVersion
    );
    float cb = sampleWithPrototype(
        mcuOffset + int(EXPECTED_Y_BYTES), int(EXPECTED_CB_BYTES),
        cbPrototypeBase, cbPrototypeCount, cbSidecarIndex,
        2, local.x >> 1, local.y, quality, coding, libraryVersion
    );
    float cr = sampleWithPrototype(
        mcuOffset + int(EXPECTED_Y_BYTES + EXPECTED_CB_BYTES), int(EXPECTED_CR_BYTES),
        crPrototypeBase, crPrototypeCount, crSidecarIndex,
        2, local.x >> 1, local.y, quality, coding, libraryVersion
    );
    outColor = vec4(yCbCrToRgb(y, cb, cr), 1.0);
}
